# Generated by Django 3.0.6 on 2020-11-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.UUIDField(default=None)),
                ('participant_name', models.CharField(default=None, max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.UUIDField(default=None)),
                ('question', models.TextField(default=None, max_length=300)),
                ('option_1', models.CharField(default=None, max_length=100)),
                ('option_2', models.CharField(default=None, max_length=100)),
                ('option_3', models.CharField(default=None, max_length=100)),
                ('option_4', models.CharField(default=None, max_length=100)),
                ('answer', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
